name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: { node-version: '14' }
      - name: Start MongoDB
        run: sudo systemctl start mongod
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
